################################################################################
#
# Module:      Check_snaketest.inc
#
# Author:      Joe White
#
# Descr:       Called by snaketest
#
# Version:    1.1  $Id: Check_snaketest.inc,v 1.3 2008/02/20 22:03:49 joe Exp $
#
# Changes:    Depreciated
#
#
#
# Still ToDo:
#
#
#            Copyright (c) 2005-2008 Stoke. All rights reserved.
#
################################################################################
<CheckData>	'Setting IXP RX_HWM_CONTROL to: 3f'
<CheckData>	' Stoke ixtest startup - PCI SERR build'
<CheckData>	'IXP register address: 98205024 '
<CheckData>	'Setting IXF Maxburst reg to: 60002'
<CheckData>	'Setting N2 POM_CRDT_INT registers to: 40'
<CheckData>	'Setting BMI per port TPA to: ff'
<CheckData>	'Setting Nitrox SPI0 Maxburst reg to: 200020'
<CheckData>	'Setting Nitrox SPI1 Maxburst reg to: 200020'
<CheckData>	'Setting Nitrox SPI0 ARB_SLC reg to: c0008'
<CheckData>	'Setting Nitrox SPI1 ARB_SLC reg to: c0008'
<CheckData>	'Setting N2 SPI0 TPA reg to: 7ff'
<CheckData>	'Setting N2 SPI1 TPA reg to: 7ff'
<CheckData>	'enable IXF ports 0 - 7'
<CheckData>	'Setting IXF MAC Xfer thresholds to: 380'
<CheckData>	'setting IXF Tx LWM to: 800'
<CheckData>	'setting IXF Rx HWM to: 1100'
<CheckData>	'setting IXF Rx LWM to: 1000'
<CheckData>	'setting IXF Tx HWM to: 900'
<CheckData>	'IXF TSTAT LAUNCH on RISING EDGE'
<CheckData>	'enable IXF backpressure'
<CheckData>	'Disable N2 Tx Continuous Packet Mode'
<CheckData>	'Setting POM valid ports register'
<CheckData>	'ixplibtest starting up'
<CheckData>	'TCAM ptr: a8c21000 '
<CheckData>	'me -f/fu/snake_load.uof load '
<CheckData>	'Downloading /fu/snake_load.uof to IXP2800 microengines'
<CheckData>	' Downloading: /fu/snake_load.uof to location: 3000000 '
<CheckData>	'ixplibtest starting up'
<CheckData>	'TCAM ptr: a8c21000 '
<CheckData>	'me start '
<CheckData>	'ixplibtest starting up'
<CheckData>	'TCAM ptr: a8c21000 '
<CheckData>	'me diag 2 '
<CheckData>	'Setting card 2 as traffic partner for testing.'
<CheckData>	'Eliminating pom int reg 3b60'
<CheckData>	'clearing statistics counts on SPI0 TX and setting the watched counter to port 0'
<CheckData>	'clearing statistics counts on SPI1 TX and setting the watched counter to port 0'
<CheckData>	'clearing statistics counts on SPI0 and SPI1 Rx'
<CheckData>	'read SPI1 Rx Packets count High/Low'
<CheckData>	'00000000'
<CheckData>	'00000000'
<CheckData>	'read SPI1 Rx byte counts High/Low'
<CheckData>	'00000000'
<CheckData>	'00000000'
<CheckData>	'read SPI1 Tx Packet count'
<CheckData>	'00000000'
<CheckData>	'read SPI1 Tx byte counts High/Low'
<CheckData>	'00000000'
<CheckData>	'00000000'
<CheckData>	'reading rx back pressure port select for SPI1'
<CheckData>	'00000000'
<CheckData>	'reading rx back pressure on SPI1 N2 to IXF RSTAT'
<CheckData>	'00000000'
<CheckData>	'reading tx back pressure port select for SPI1 4to0'
<CheckData>	'00000000'
<CheckData>	'reading tx back pressure IXF to N2 TSTAT'
# Changes <CheckData>	'994AAA08'
<CheckData>	'Setting all Cavium Ports to "pass through"'
<CheckData>	'Enabling all IXF ports'

