################################################################################
#
# Module:      null.inc
#
# Author:      Joe White
#
# Descr:       Called by default if a value is not set
#
# Version:    1.1 $Id: null.inc,v 1.2 2008/02/20 22:03:49 joe Exp $
#
# Changes:    Created 10/19/06
#
#
# Still ToDo:
#
#
#            Copyright (c) 2006-2008 Stoke. All rights reserved.
#
################################################################################
<Msg>	"."
